name: programmers_badge_action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 5 * * 1-5'
  repository_dispatch:
    types: [ trigger-workflow ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Java program
        env:
          PROGRAMMERS_EMAIL: ${{ secrets.PROGRAMMERS_EMAIL }}
          PROGRAMMERS_PASSWORD: ${{ secrets.PROGRAMMERS_PASSWORD }}
        run: ./gradlew run
      - name: Commit and Push changes
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_NAME: ${{ secrets.GIT_NAME }}
        run: |
          git config --global user.email "${{ env.GIT_EMAIL }}"
          git config --global user.name "${{ env.GIT_NAME }}"
          git add result.svg
          git commit -m "Update badge"
          git push